version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/source/requirements.txt

apt_packages:
  - gdal-bin
  - libgdal-dev

# Export GDAL environment variables
environment:
  CPLUS_INCLUDE_PATH: "/usr/include/gdal"
  C_INCLUDE_PATH: "/usr/include/gdal"
