defaults:
  - finetune_halle.yaml

name: debug-halle
trainer:
  fast_dev_run: True
data:
  batchsize: 16 
  num_workers: 1         # Number of workers in dataloader
  train_indices: [0, 1, 2, 3, 4, 5, 6, 7]
  val_indices: [8, 9]