defaults:
 - train_halle.yaml

seed: 4321

model:
  pretrained_model: Unet-resnet18_epochs=209_lr=0.0001_width=224_bs=32_divby=255_custom_color_augs_k=0_jitted.pt 
  lr: 0.00003 # choose a smaller learning rate
  freeze_layers: True