defaults:
 - train_halle.yaml

name: finetune-halle

seed: 4321

pretrained:
  model: Unet-resnet18_epochs=209_lr=0.0001_width=224_bs=32_divby=255_custom_color_augs_k=0_jitted.pt 

model:
  lr: 0.00003 # choose a smaller learning rate
  freeze_layers: True

data:
  batchsize: 2
  train_indices: [0, 1, 2, 3, 4, 5, 6, 7,]
  val_indices: [8, 9]
  shuffle: False # should not be used with fixed indices

trainer:
  devices: 1 