name: inference-halle
output_dir: results

data:
  _target_: deeptrees.dataloading.datamodule.TreeCrownDelineationDataModule
  rasters: /work/ka1176/shared_data/2024-ufz-deeptree/polygon-labelling/pool_tiles  # directory with raster images
  masks: null
  outlines: null
  distance_transforms: null
  batch_size: 1          # dataloader batch size
  test_indices: null     # set to null to process the whole folder
  ndvi_config:
    concatenate: True    # If True, concatenate NDVI
    rescale: False       # If True, rescale to [0, 1]
    red: 0               # Index of Red channel
    nir: 3               # Index of Infrared channel
  divide_by: 255         # divisor
  dilate_outlines: False # dilate the outlines by number of pixels
  augment_eval:
    Pad:
      padding: 6 
  ground_truth_config:
    labels: null
  num_workers: 8         # Number of workers in dataloader
pretrained_model: /work/ka1176/caroline/gitlab/deeptrees/experiments/finetune-halle/2024-11-25_09-32-21/unet-halle_jitted.pt
  
model:
  _target_: deeptrees.model.deeptrees_model.DeepTreesModel
  num_backbones: 1
  in_channels: 5         # Number of input channels / bands of the input image
  architecture: Unet     # segmentation model architecture
  backbone: resnet18     # backbone
  apply_sigmoid: False   # sigmoid function applied to masks and outlines
  postprocessing_config:
    min_dist: 10 # minimum distnace in pixels between local maxima during feature extraction
    mask_exp: 2
    outline_multiplier: 5
    outline_exp: 1
    dist_exp: 0.5
    area_min: 3 # smaller polygons are discarded
    sigma: 2 # standard deviation of Gaussian filter during feature extraction
    label_threshold: 0.5 # minimum height of local maxima during feature extraction
    binary_threshold: 0.1 # threshold value for the feature map, lower is background
    simplify: 0.3 # polygon simplification distance, vertices closer than this value are simplified
    active_learning: True # calculate entropy heatmap
    save_entropy_maps: True  # save entropy heatmap
    save_predictions: True  # save predictions (mask, outlines, distance transform)
  # TODO
  #  subsample: False # if True, polygon extraction works at half the resolution of the model output. Use this for speedup at the cost of accuracy.
  #  upsample: 1.0 # Input to the network will be upsampled bilinearly by the given factor
  #  sigmoid: False # if True, sigmoid activation will be applied to masks and outlines
  #  stride: null # Stride used in applying the network to the image

logdir: ${hydra.run.dir} # this is where we find logs, trained models, predictions
model_name: unet-halle # short and memorable model name
seed: null               # Fix random seed 

crs: EPSG:25832
polygon_file: treecrowns.sqlite
baumkataster_file: /work/ka1176/shared_data/2024-ufz-deeptree/halle-baumkataster/itc005211130105323_point.shp
baumkataster_intersection_file: treecrowns_baumkataster.sqlite

callbacks: {}

trainer:
  _target_: lightning.Trainer
  devices: 1               # Number of devices (GPUs) to use
  accelerator: auto        # Choose GPU if available
  enable_progress_bar: False

hydra:
  job:
    chdir: True
  run:
    dir: outputs/${output_dir}/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}